name: Build and Run Tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
        
    - name: Build code
      run: dotnet build --configuration Release 
      working-directory: ./src
        
    - name: Run tests
      run: dotnet test --no-build -v n --configuration Release
      working-directory: ./src
