using FactoryBot.DSL.Attributes;
using FactoryBot.Generators;

namespace FactoryBot.DSL.Builders
{
    /// <summary>
    /// Builder for BuildCustom method
    /// </summary>
    public class CustomConstructBuilder : BotConfigurationBuilder
    {
        /// <summary>
        /// Keeps previously defined generator untouched
        /// </summary>
        /// <typeparam name="T">Type of generating value</typeparam>
        /// <returns>Value generated by previously defined generator</returns>
        [Generator(typeof(KeepGenerator))]
        public T Keep<T>() => default!;
    }
}